site_name:        MatrixEnsembles.jl
repo_url:         https://github.com/iitis/MatrixEnsembles.jl.git
site_description: A Julia package for studying random matrix ensembles.
site_author:      Łukasz Pawela

theme: readthedocs

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
- assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Home: index.html
